package com.example.jacek.gympartner.SQLite;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by Jacek on 05.02.2017.
 */
public class GymDbHelper extends SQLiteOpenHelper {
    public static final String LOG_TAG = GymContract.class.getSimpleName();
    public static final int DATABASE_VERSION = 1;
    public static final String DATABASE_NAME = "Gym.db";
    public GymDbHelper(Context context) {
        super(context,DATABASE_NAME,null,DATABASE_VERSION);
    }

    private static final String SQL_DELETE_ENTRIES =
            "DROP TABLE IF EXISTS " + GymContract.GymEntry.TABLE_NAME;
    @Override
    public void onCreate(SQLiteDatabase db) {
        String DATABASE_CREATE =
                "CREATE TABLE if not exists " + GymContract.GymEntry.TABLE_NAME + " (" +
                        GymContract.GymEntry.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT," +
                        GymContract.GymEntry.COLUMN_NAME + " TEXT NOT NULL," +
                        GymContract.GymEntry.COLUMN_KIND + " TEXT ," +
                        GymContract.GymEntry.COLUMN_URL + " TEXT," +
                        GymContract.GymEntry.COLUMN_SCORE + " TEXT NOT NULL DEFAULT 0," +
                        GymContract.GymEntry.COLUMN_SERIES + " INTEGER NOT NULL DEFAULT 1," +
                        GymContract.GymEntry.COLUMN_REP + " INTEGER" +
                        ");";
        db.execSQL(DATABASE_CREATE);
        //3 dni       ---- 1 LEVEL -----
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Pompki','Klatka piersiowa','https://www.youtube.com/watch?v=bwnidT3CB_Q',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Pompki na poręczach','Triceps','https://www.youtube.com/watch?v=Cufsu3IHhCo',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Odwrotne wiosłowanie','Plecy','https://www.youtube.com/watch?v=8qCn76yKhro',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha leżąc','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Unoszenie kolan','Dolna część mięśni brzucha','https://www.youtube.com/watch?v=Htx9Z8ZkiCg',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Skręty tułowia','Mięśnie skośne brzucha','https://www.youtube.com/watch?v=i7smKA3mgBU',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Przysiady bez sztangi','Uda','https://www.youtube.com/watch?v=NEduXlZ8zSk&t',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Wspięcia na palce','Mięśnie łydek','https://www.youtube.com/watch?v=Wri0VppFWCY',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Podciąganie na drążku','Mięśnie grzbietu','https://www.youtube.com/watch?v=7hM1iriAxx8',0,3)");
        // 3 dni    ---- 2 LEVEL -----
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=lvGciMRi_zU',0,5,'8-6 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Podciąganie z szerokim chwytem','Mięśnie grzbietu','https://www.youtube.com/watch?v=X5eptRVZUno',0,4,'10-6 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie sztangi sprzed głowy','Mięśnie naramienne','https://www.youtube.com/watch?v=cQg2f3xfJq0',0,3,'10-6 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion ze sztangą','Biceps','https://www.youtube.com/watch?v=zvoKbd3hVnQ',0,3,'10-8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie','Triceps','https://www.youtube.com/watch?v=GTYZFPoCoIo',0,3,'10-8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przysiad z obciążeniem','Uda','https://www.youtube.com/watch?v=nnk9KItK938',0,4,'10-8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nóg leżąc','Mięsień dwugłowy uda','https://www.youtube.com/watch?v=xhTprFWnJQw&t',0,3,'10-8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce na maszynie','Mięśnie łydek','https://www.youtube.com/watch?v=mbyTbDJBsR8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha skos dół','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,3)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,3,'10-8 powtorzen')");
        //pn i czwartek    ---- 3 LEVEL ----- 19
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przysiad z obciążeniem','Uda','https://www.youtube.com/watch?v=nnk9KItK938',0,5,'8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Prostowanie nóg','Mięśnie czworogłowe uda','https://www.youtube.com/watch?v=JD4s25JoE2A&t=1s',0,5,'12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nóg leżąc','Mięsień dwugłowy uda','https://www.youtube.com/watch?v=xhTprFWnJQw&t',0,5,'8-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce na maszynie','Mięśnie łydek','https://www.youtube.com/watch?v=mbyTbDJBsR8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=lvGciMRi_zU',0,5,'8-5 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Rozpiętki z hantlami na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=aHG78PBG8d8',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha skos dół','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,4)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Unoszenie nóg w leżeniu na ławce','Mięśnie brzucha dolna część','https://www.youtube.com/watch?v=uDLU8MfMFDc',0,4)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'15 powtorzen')");
        // wt i pt 28
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie zza głowy','Mięśnie naramienne - przednia część','https://www.youtube.com/watch?v=4zL7YlXxZ8c',0,5,'8-6 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie hantli w bok','Mięśnie naramienne - boczna część','https://www.youtube.com/watch?v=vU50wUxydDo',0,8,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Podciąganie na drążku za głowę','Mięsień najszerszy grzbietu','https://www.youtube.com/watch?v=jlBhe0kffYo',0,6,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wiosłowanie sztangą w opadzie','Górna partia pleców','https://www.youtube.com/watch?v=PaqvesLOcpA',0,5,'12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion ze sztangą','Biceps','https://www.youtube.com/watch?v=zvoKbd3hVnQ',0,5,'8-6 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion z hantlami siedząc','Biceps','https://www.youtube.com/watch?v=svpIyTIsn-U',0,5,'8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion z hantlami siedząc na skośnej ławce','Biceps','https://www.youtube.com/watch?v=ruNK313gW88',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie siedząc','Triceps','https://www.youtube.com/watch?v=pV5vQNtFbmw',0,5,'12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie leżąc','Triceps','https://www.youtube.com/watch?v=GTYZFPoCoIo&t',0,5,'10-12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'15 powtorzen')");
        //pn i czw      ---- 4 LEVEL ----- 38
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przysiad z obciążeniem','Uda','https://www.youtube.com/watch?v=nnk9KItK938',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Prostowanie nóg','Mięśnie czworogłowe uda','https://www.youtube.com/watch?v=JD4s25JoE2A&t=1s',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nóg leżąc','Mięsień dwugłowy uda','https://www.youtube.com/watch?v=xhTprFWnJQw&t',0,5,'12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przysiad z wykrokiem','Uda','https://www.youtube.com/watch?v=NnJqBiQ1bCc',0,5,'8-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce na maszynie','Mięśnie łydek','https://www.youtube.com/watch?v=mbyTbDJBsR8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce siedząc','Dolna część łydki i płaszczkowaty','https://www.youtube.com/watch?v=5aYNiTFd8PM',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha skos dół','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,5)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie nóg w leżeniu na ławce','Mięśnie brzucha dolna część','https://www.youtube.com/watch?v=uDLU8MfMFDc',0,5,'50 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Skręt tułowia','Mięśnie przedramienia','https://www.youtube.com/watch?v=zwCzZMCCGSE',0,5,'50 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'12 powtorzen')");
        //wt i pt
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Podciąganie na drążku','Mięśnie grzbietu','https://www.youtube.com/watch?v=7hM1iriAxx8',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wiosłowanie sztangą w opadzie','Górna partia pleców','https://www.youtube.com/watch?v=PaqvesLOcpA',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wiosłowanie końcem sztangi w opadzie','Mięśnie grzbietu','https://www.youtube.com/watch?v=_7uJakDkVCM',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=lvGciMRi_zU',0,5,'12-6 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie na ławeczce skośnej','Górna część klatki piersiowej','https://www.youtube.com/watch?v=FoP4sLFziF0',0,5,'8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Rozpiętki z hantlami na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=aHG78PBG8d8',0,10,'12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przenoszenie hantla nad głową','Klatka piersiowa','https://www.youtube.com/watch?v=JpVnRFa1gJU',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie zza głowy','Mięśnie naramienne - przednia część','https://www.youtube.com/watch?v=4zL7YlXxZ8c',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie hantli w bok','Mięśnie naramienne - boczna część','https://www.youtube.com/watch?v=vU50wUxydDo',0,5,'8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie hantli w bok w opadzie','Tylnia część mięśni naramiennych','https://www.youtube.com/watch?v=dIbE_iYjMnc',0,5,'8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'15-10 powtorzen')");
        //sr i sob
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Prostowanie ramion na wyciągu','Triceps','https://www.youtube.com/watch?v=WBwvIlLTm00',0,5,'10-8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie siedząc','Triceps','https://www.youtube.com/watch?v=pV5vQNtFbmw',0,5,'12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie leżąc','Triceps','https://www.youtube.com/watch?v=GTYZFPoCoIo&t',0,5,'10-8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion z hantlami siedząc na skośnej ławce','Biceps','https://www.youtube.com/watch?v=ruNK313gW88',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion na modlitewniku','Biceps','https://www.youtube.com/watch?v=Zeb68B5sC_0',0,5,'8 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramienia z hantlem','Biceps','https://www.youtube.com/watch?v=bLcvij6UXP4',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce na maszynie','Mięśnie łydek','https://www.youtube.com/watch?v=mbyTbDJBsR8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce siedząc','Dolna część łydki i płaszczkowaty','https://www.youtube.com/watch?v=5aYNiTFd8PM',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha skos dół','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,5)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie nóg w leżeniu na ławce','Mięśnie brzucha dolna część','https://www.youtube.com/watch?v=uDLU8MfMFDc',0,5,'50 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Skręt tułowia','Mięśnie przedramienia','https://www.youtube.com/watch?v=zwCzZMCCGSE',0,5,'50 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'12 powtorzen')");
        //pn i czw  ---- 5 LEVEL -----
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przysiad z obciążeniem','Uda','https://www.youtube.com/watch?v=nnk9KItK938',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nóg leżąc','Mięsień dwugłowy uda','https://www.youtube.com/watch?v=xhTprFWnJQw&t',0,5,'10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Prostowanie nóg','Mięśnie czworogłowe uda','https://www.youtube.com/watch?v=JD4s25JoE2A&t=1s',0,10,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przysiad z wykrokiem','Uda','https://www.youtube.com/watch?v=NnJqBiQ1bCc',0,10,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce na maszynie','Mięśnie łydek','https://www.youtube.com/watch?v=mbyTbDJBsR8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha skos dół','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,5)");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie nóg w leżeniu na ławce','Mięśnie brzucha dolna część','https://www.youtube.com/watch?v=uDLU8MfMFDc',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce siedząc','Dolna część łydki i płaszczkowaty','https://www.youtube.com/watch?v=5aYNiTFd8PM',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Skręt tułowia','Mięśnie przedramienia','https://www.youtube.com/watch?v=zwCzZMCCGSE',0,1,'50-100 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'15 powtorzen')");
        //wt i pt
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=lvGciMRi_zU',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Podciąganie na drążku','Mięśnie grzbietu','https://www.youtube.com/watch?v=7hM1iriAxx8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie na ławeczce skośnej','Górna część klatki piersiowej','https://www.youtube.com/watch?v=FoP4sLFziF0',0,5,'15-12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wiosłowanie sztangą w opadzie','Górna partia pleców','https://www.youtube.com/watch?v=PaqvesLOcpA',0,5,'15-12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Rozpiętki z hantlami na ławeczce','Klatka piersiowa','https://www.youtube.com/watch?v=aHG78PBG8d8',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wiosłowanie końcem sztangi w opadzie','Mięśnie grzbietu','https://www.youtube.com/watch?v=_7uJakDkVCM',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Przenoszenie hantla nad głową','Klatka piersiowa','https://www.youtube.com/watch?v=JpVnRFa1gJU',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie zza głowy','Mięśnie naramienne - przednia część','https://www.youtube.com/watch?v=4zL7YlXxZ8c',0,5,'15-12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie hantli w bok','Mięśnie naramienne - boczna część','https://www.youtube.com/watch?v=vU50wUxydDo',0,5,'15-12 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Unoszenie hantli w bok w opadzie','Tylnia część mięśni naramiennych','https://www.youtube.com/watch?v=dIbE_iYjMnc',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wspięcia na palce na maszynie','Mięśnie łydek','https://www.youtube.com/watch?v=mbyTbDJBsR8',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+") VALUES('Spięcia brzucha skos dół','Górna część mięśni brzucha','https://www.youtube.com/watch?v=VVcm4LdmIwM',0,5)");
        //sr i sob
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Prostowanie ramion na wyciągu','Triceps','https://www.youtube.com/watch?v=WBwvIlLTm00',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion z hantlami siedząc na skośnej ławce','Biceps','https://www.youtube.com/watch?v=ruNK313gW88',0,5,'12-10 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie siedząc','Triceps','https://www.youtube.com/watch?v=pV5vQNtFbmw',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion na modlitewniku','Biceps','https://www.youtube.com/watch?v=Zeb68B5sC_0',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Wyciskanie francuskie leżąc','Triceps','https://www.youtube.com/watch?v=GTYZFPoCoIo&t',0,5,'10-15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramienia z hantlem','Biceps','https://www.youtube.com/watch?v=bLcvij6UXP4',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie ramion ze sztangą nachwytem','Mięśnie przedramienia','https://www.youtube.com/watch?v=vAYSB8I0LRg&t',0,5,'15 powtorzen')");
        db.execSQL("INSERT INTO "+GymContract.GymEntry.TABLE_NAME+"("+GymContract.GymEntry.COLUMN_NAME+","+GymContract.GymEntry.COLUMN_KIND+","+GymContract.GymEntry.COLUMN_URL+","+GymContract.GymEntry.COLUMN_SCORE+","+GymContract.GymEntry.COLUMN_SERIES+","+GymContract.GymEntry.COLUMN_REP+") VALUES('Uginanie nadgarstków','Mięśnie przedramienia','https://www.youtube.com/watch?v=YGf77jdjxd8',0,5,'15 powtorzen')");
    }
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL(SQL_DELETE_ENTRIES);
        onCreate(db);
    }
    @Override
    public void onDowngrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        onUpgrade(db,oldVersion,newVersion);
    }
}